spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
         ATCONTEXT_WRITE_CHANNEL:
          destination: ATCONTEXT
          contentType: application/json
        #ENTITY_READ_CHANNEL:
         # destination: ENTITY
         # contentType: application/json
         # group: entity

               
          