version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <SET YOUR LOCAL IP OF YOUR HOST HERE>
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgres:
    image: mdillon/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  atctxsrv:
    image: AtContextServer-0.0.1-SNAPSHOT
    ports:
      - "27015"
    depends_on:
      - kafka
      - eureka
  cfgsrv:
    image: config-server-0.0.1-SNAPSHOT
    ports:
      - "8888"
    depends_on:
      - eureka
  emgr:
    image: EntityManager-0.0.1-SNAPSHOT
    ports:
      - "1025"
    depends_on:
      - kafka
      - eureka
  eureka:
    image: eureka-server-0.0.1-SNAPSHOT
    ports:
      - "8761"
  gateway:
    image: gateway-0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    depends_on:
      - eureka
  histmgr:
    image: HistoryManager-0.0.1-SNAPSHOT
    ports:
      - "1040"
    depends_on:
      - kafka
      - gateway
      - eureka
  qrymgr:
    image: QueryManager-0.0.1-SNAPSHOT
    ports:
      - "1026"
    depends_on:
      - kafka
      - postgres
      - eureka
  regmgr:
    image: RegistryManager-0.0.1-SNAPSHOT
    ports:
      - "1030"
    depends_on:
      - kafka
      - postgres
      - gateway
      - eureka
  stomgr:
    image: StorageManager-0.0.1-SNAPSHOT
    ports:
      - "1029"
    depends_on:
      - kafka
      - postgres
      - eureka
  sbsmgr:
    image: SubscriptionManager-0.0.1-SNAPSHOT
    ports:
      - "2025"
    depends_on:
      - kafka
      - eureka
