spring:
  cloud:
    stream:
      kafka:
        binder:
     #     brokers: localhost:9092
      #bindings:
        #ENTITY_READ_CHANNEL:
         # destination: ENTITY
         # contentType: application/json
         # group: entity

               
          